### ISSUE TITLE
[rest] /Wallet is broken

### ISSUE THREAD

**Issue by blu3beri** [hyperledger/aries-framework-javascript-ext#123]
It might be because I am not on the latest version but the `<BASE>/wallet` seems to be broken:

<img width="417" alt="image" src="https://user-images.githubusercontent.com/61358536/174314627-7a148aa9-9186-4693-ba9e-12b33958e155.png">

**Comment by janrtvld** [comment]
The wallets part is custom logic from the demo. The OpenApi fails because it fails to notice the prefix that is added from the original app (actual route is `/demo/wallets`). 

Will look into this when we switch over to TSOA.

**Comment by TimoGlastra** [comment]
We should probably close this and open it in https://github.com/animo/animo-demo then?

**Comment by janrtvld** [comment]
Its an issue in the rest api that the openApi spec is invalid when you pass your own express server to the `setupServer`.

**Comment by TimoGlastra** [comment]
Will this be fixed by #148 ?

**Comment by janrtvld** [comment]
Yes
