### ISSUE TITLE
[rest] Opening the /credentials/offer-credential in the UI errors

### ISSUE THREAD

**Issue by blu3beri** [hyperledger/aries-framework-javascript-ext#124]
1. Click on the /credentials/offer-credential
2. Scroll to the top
3. The following error is displayed: 
<img width="1626" alt="image" src="https://user-images.githubusercontent.com/61358536/174315721-2c5f6b78-fcc5-47cf-a62e-0e0d0c59a793.png">

**Comment by TimoGlastra** [comment]
@janrtvld this is fixed by #148 right?
