### ISSUE TITLE
[rest] no peer dependencies

### ISSUE THREAD

**Issue by jakubkoci** [hyperledger/aries-framework-javascript-ext#142]
"Starting Own Server" section in docs mentions "To get started, make sure you have set up the correct version of Aries Framework JavaScript" with the following command:

```
npm info "@aries-framework/rest" peerDependencies
```

But that command doesn't return anything. I wanted to use the extension with the framework, but I was a bit confused about what exact version of framework is compatible? It is the version `0.1.0`?

**Comment by TimoGlastra** [comment]
Ah I think we moved away from peer dependencies as you can now also use the rest package as cli, in which case you won't install the node/core packages yourself. We should probably remove this from the README

Are you willing to open a PR for this?

But yes, the current supported version is 0.1.0 (we should probably also add that to the readme!).

@amanji has been working on 0.2.0 support, but not sure on the status of that

**Comment by amanji** [comment]
Sorry this took a bit of a backseat to work on updates to Bifold. Will continue working on this. @jakubkoci Do you want to coordinate on how to remove the peer dependencies?

**Comment by TimoGlastra** [comment]
Yes It's just an update to the readme. That would be appreciated, thanks!
