### ISSUE TITLE
[hooks] useCredentialsByState inverse filter

### ISSUE THREAD

**Issue by morrieinmaas** [hyperledger/aries-framework-javascript-ext#147]
While using the useCredentialsByState hook I came across a use-case where it would be handy to have inverse filters. Instead of querying for eg `useCredentialByState('done')` it would be handy to be able to retrieve for all states states but certain state(s).
This could also be a list. 

Proposal:
* allow input param to be a list of states instead of just a single state -> `useCredentialByState(["done", "offer-sent"])`
* also allow to negate that input param list along the lines of `useCredentialByState([!"done", !"offer-sent"])` which retrieves the records for all states but 'done" and 'offer-sent'

This might also apply to proofs and connections.

**Comment by TimoGlastra** [comment]
I agree with the first proposal, that would be useful (we're supporting that in the assertState method filter in AFJ). 

the second one won't work like this (`!"done"` equals false) and would probably need a new method. However you could also do something like `Object.keys(CredentialState).filter(s => s !== CredentialState.Done)` and pass that to the use method.

**Comment by morrieinmaas** [comment]
yes nice!. second one was just for lack of better notation, but it looks like you got my intention there.

**Comment by morrieinmaas** [comment]
Also I'm happy to work on this
