### ISSUE TITLE
[rest] Add websocket event server

### ISSUE THREAD

**Issue by TimoGlastra** [hyperledger/aries-framework-javascript-ext#155]
Currently you can provide a webhookUrl to the AFJ rest agent that we will send webhook events to whenever an event is emitted on the agent. Listening to webhook events means you need to set up your own server that can listen to those webhooks. In some cases it may be desired to get the events from the rest api through a websocket interface. This means you don't need to host a server and can connect directly through a websocket client.

We can reuse the same server that is used for the REST api for the websocket events. This means no extra servers need to be spawned. You can see in the mediator.ts from AFJ how the upgrade to websocket works: https://github.com/hyperledger/aries-framework-javascript/blob/main/samples/mediator.ts#L89. This can be added in the `server.ts` file.

The websocket handling can be implemented using the `ws` package: https://npmjs.com/package/ws. We can use this to listen to incoming websocket connections, and we can emit..

1. Create an `EventHandler` class that exposes a method to send events. The `EventHandler` should keep track of the websocket connections, and the webhook url.
2. Register the websocket server in the server.ts. Whenever an upgrade is made (See mediator.ts example) we should register the connection on the event handler. Whenever the ocnnection is closed, we should unregister the connection on the event handler.
3. Whenever the event handler is called to send an event it will send the event to the webhookUrl (if registered) and all connected websocket clients.
4. Document how the websocket server can be used in the rest README file.

> Note: events are currently only emitted to the webhook Url for topics that are implemented in the rest api. We listen for them in the `server.ts` file.

**Comment by rapaktech** [comment]
I think we can close this now @TimoGlastra
