### ISSUE TITLE
[rest] Add filter to get credentials endpoint

### ISSUE THREAD

**Issue by TimoGlastra** [hyperledger/aries-framework-javascript-ext#157]
It is currently possible to provide filters to the `/connections` to narrow down the results returned from the framework. We should add filters to the `/credentials` endpoint.

We can take an example for the implementation from the `ConnectionController.getAllConnections` method and add `@Query` filters.

- [ ] Add filters to the `CredentialController.getAllCredentials` endpoint
- [ ] Write tests for the different filters in credentials.test.ts
- [ ] Make sure the swagger ui correctly displays the different queries, ideally with some documentation on possible values

### Filters

Filters should be based on the credential record tags, as that is what we can filter on. Proposed filters
-  threadId
- connectionId
- state
- credentialId(s)

**Comment by rapaktech** [comment]
Working on this, I discovered that there's already an enpoint for getting crendentials by credential id... I assume this negates the need for the filter?

**Comment by TimoGlastra** [comment]
I think they can be complementary. Get by id if you know the id, and get all with a filter if you don't know it yet

**Comment by rapaktech** [comment]
I meant the 'filter by credentialId'

**Comment by rapaktech** [comment]
Would there be a need for a get all by credentialId filter?

**Comment by TimoGlastra** [comment]
Ah. Yes 👍

**Comment by rapaktech** [comment]
Okay
