### ISSUE TITLE
[Question] Initialising the Agent in a latter stage

### ISSUE THREAD

**Issue by icc-romeu** [hyperledger/aries-framework-javascript-ext#230]
Hi, I have read the docs and I saw that you need a fully initialised agent at app startup. But that means that you need to open the wallet and already have the wallet master key. What if I want to ask the user set it up? How can I manage that? I saw this:

```
 if (!agent) return <LoadingComponent />

  return <AgentProvider agent={agent}>/* Your app here */</AgentProvider>
```

So, you are not showing anything until the wallet is set up. I was thinking on starting the app, and once wallet is ready, adding the provider to the app but, is there another way where I do not need to do that?

**Comment by TimoGlastra** [comment]
Currently you need to provide an initialized agent, so if you want to delay initializing the agent, you'd have to delay adding the AgentProvider
