### ISSUE TITLE
[rest] Request OOB proof and Offer OOB credential should use d_m instead of c_i for encoded message

### ISSUE THREAD

**Issue by TimoGlastra** [hyperledger/aries-framework-javascript-ext#64]
Currently the urls returned by the created OOB proof and offer OOB credential use `c_i` (which stands for  Connection Invitation). Although there is not a strict standard, we should use `d_m` (which stands for DIDComm Message I believe). This is also what Trinsic uses

**Comment by TimoGlastra** [comment]
@janrtvld

**Comment by swcurran** [comment]
Sorry to be late on this, but for OOB, shouldn't the query parameters defined [here](https://github.com/hyperledger/aries-rfcs/tree/main/features/0434-outofband#standard-out-of-band-message-encoding) in the RFC be used?  Or is this at a different level?

**Comment by TimoGlastra** [comment]
Yes for the OOB protocol it does, but we don't support the OOB protocol yet. This is what Trinsic and other wallets are using for the pre OOB protocol way of doing OOB. This way it would be easy for us to detect what protocol to use (`oob` = OOB protocol, `d_m` = AIP OOB, `c_i` = AIP 1.0 connection)
